//! Test vectors shared by the Python reference and this crate.
//!
//! GENERATED by `python3 fakes/test_bridge.py --write-vectors`. Do not edit by hand: edit
//! `fakes/bridge.py` / `fakes/test_bridge.py` and regenerate, so the two implementations cannot
//! disagree silently (see `testdata/vectors.json` for the same data in JSON).

pub const PROTOCOL_VERSION: u16 = 1;
pub const MAGIC: [u8; 4] = [0x55, 0x4D, 0x42, 0x52]; // "UMBR"

/// ((guest_x, guest_y), (host_x, host_y), (cell_i, cell_j)) in a region at (1000, 2000), 64x64, 8 m cells.
pub const POSITIONS: &[(f32, f32, f32, f32, i32, i32)] = &[
    (260.0, 196.0, 1032.5000, 2487.5000, 4, 60),
    (0.0, 0.0, 1000.0000, 2512.0000, 0, 63),
    (4096.0, 4096.0, 1512.0000, 2000.0000, 63, 0),
    (4096.0, 0.0, 1512.0000, 2512.0000, 63, 63),
];

/// (guest_theta, host_yaw, dir_x, dir_y) — dir is Veloren's `Dir` for that yaw.
pub const ANGLES: &[(f32, f32, f32, f32)] = &[
    (0.0000000000, -1.5707963268, 1.0000000000, 0.0000000000),
    (1.5707963268, 3.1415926536, -0.0000000000, -1.0000000000),
    (3.1415926536, 1.5707963268, -1.0000000000, 0.0000000000),
];

/// (i, j, height_m, kind) for a 5x5 grid, row-major, sea level 0, classified by the reference.
pub const CLASSIFICATION_NX: usize = 5;
pub const CLASSIFICATION_NY: usize = 5;
pub const CLASSIFICATION: &[(i32, i32, f32, u8)] = &[
    (0, 0, -3.0, 1),
    (1, 0, 0.9, 2),
    (2, 0, 1.8, 3),
    (3, 0, 4.0, 6),
    (4, 0, 150.0, 6),
    (0, 1, 5.0, 6),
    (1, 1, 5.0, 5),
    (2, 1, 5.0, 4),
    (3, 1, 5.0, 6),
    (4, 1, 150.0, 6),
    (0, 2, 5.0, 4),
    (1, 2, 5.0, 6),
    (2, 2, 5.0, 4),
    (3, 2, 5.0, 6),
    (4, 2, 150.0, 6),
    (0, 3, 5.0, 6),
    (1, 3, 13.0, 6),
    (2, 3, 5.0, 6),
    (3, 3, 5.0, 6),
    (4, 3, 150.0, 6),
    (0, 4, 150.0, 6),
    (1, 4, 150.0, 6),
    (2, 4, 150.0, 6),
    (3, 4, 150.0, 6),
    (4, 4, 150.0, 7),
];

/// (tile_units, tile_m, u2m)
pub const CONSTANTS: (f32, f32, f32) = (64.0, 8.0, 0.125);
/// (stale_ms, dead_ms)
pub const WATCHDOG: (f64, f64) = (600, 2000);
/// A packed entity from the reference, hex-encoded (id=0x01020304, kind=2, team=3, flags=5, ...).
pub const ENTITY_SAMPLE_HEX: &str = "04030201020305000000803f0000004000004040000080400000a0400000c0400000e0400000003f";
/// The first 64 bytes of a packed state payload from the reference, hex-encoded.
pub const STATE_SAMPLE_HEX: &str = "2a000000bc02000005000300ffff00000000803f0000004000000000000000000000000002000100000000000000000000000000000000000000000000000000";
